version: "3.8"

networks:
  blog_network:  
services:
  # Your application service
  server_app:
    build: ./server_app
    ports:
      - "3000:3000"
    networks:
      - blog_network

  # Your database service
  db:
    build: ./db
    ports:
      - "5432:5432"
    networks:
      - blog_network